### ISSUE TITLE
create handler command

### ISSUE THREAD

**Issue by cohix** [suborbital/subo#134]
Would love to be able to run `subo create handler /foo` and have it added to the directive.

Some potential flags: --method, --stream, --steps

**Comment by MacklinEngineering** [comment]
Steps: 
- [ ] move the directive file from /builder into subo/subo/util
- [ ] Read in and parse (deserialize) the Directive.yml file (subo already does this)

- [ ] Construct the new handler using the values provided by the user with good defaults otherwise

- [ ] Append the new handler to the currently list of handlers

- [ ] Write out (serialize) the Directive.yml file (subo already does this)

**Comment by MacklinEngineering** [comment]
Notes: Recreating the directive struct however, with my new headers appended. 

Directive file already exists in subo. 

Steps:
Unmarshall
Create Handler
Append Handler to directive file
Re-Marshall entire directive

Q: What does marshaling mean and do?
A: Marshaling = converting convert a Golang Struct into Byte data and "unmarshaling" does the exact opposite - takes byte data and converts it into a struct.

**Comment by MacklinEngineering** [comment]
To test:
run `make subo` in subo folder
run `subo create handler /:resource` to create a handler in that directory
