### ISSUE TITLE
Have subo create commands add .gitignore files

### ISSUE THREAD

**Issue by calebschoepp** [suborbital/subo#56]
I think it would be beneficial for the `subo create` commands to also scaffold out a `.gitignore` file. I felt like this was an issue because when I ran `subo create project` my Rust target directory was being tracked.

These `.gitignore` files could be added at the project level, the runnable level, or both. Some things that might be nice to exclude would include:

- `target` directories
- The equivalent for Swift (not familiar with the language)
- Maybe `runnables.wasm.zip`. I'm not sure if tracking this artifact of the build process is idiomatic or not. Regardless, it's inclusion or absence in the `.gitignore` would be a good guide to new developers like me on whether it is idiomatic to track or not.

**Comment by cohix** [comment]
Yep, this makes sense for sure. If you would like to do this yourself, you can add the `.gitignore` to the `templates/project` folder in this repo. I think the list you have there makes sense, the Swift `.build` directory should be included as well. May as well add `node_modules` since TypeScript/AssemblyScript support is coming soon.

If not, I'll try to get this in before the next release.

**Comment by calebschoepp** [comment]
> Yep, this makes sense for sure. If you would like to do this yourself, you can add the `.gitignore` to the `templates/project` folder in this repo. I think the list you have there makes sense, the Swift `.build` directory should be included as well. May as well add `node_modules` since TypeScript/AssemblyScript support is coming soon.
> 
> If not, I'll try to get this in before the next release.

Yep, I'm happy to pick this up and submit a PR. It'll be a good chance to acquaint myself with the codebase.
