### ISSUE TITLE
"failed to get CurrentBuildContext" when running "subo create project" in user home folder

### ISSUE THREAD

**Issue by FanaHOVA** [suborbital/subo#77]
To reproduce:
- Install subo 
- `cd ~`
- `subo create project name`

Returns:
```
Error: 🚫 failed to get CurrentBuildContext: failed to getRunnableDirs: failed to list files in .Trash: open /Users/fana/.Trash: operation not permitted
```

Expected result:
Project is created successfully

Hardware specs:
- 2.8 GHz Quad-Core Intel Core i7
- 16 GB 2133 MHz LPDDR3
- Docker Desktop 3.5.1

**Comment by cohix** [comment]
@FanaHOVA Thanks for filing.

The issue resides here: https://github.com/suborbital/subo/blob/main/builder/context/buildcontext.go#L117

When creating the `BuildContext`, the `getRunnableDirs` function attempts to look inside each directory to see if there's a `.runnable.yaml` file. If that lookup fails, we error the whole process. I'd suggest we just `continue` when that error occurs instead, which would just skip any directory that we don't have permission to read.

Let me know if you'd like to take this one on, otherwise I'll pick it up before the next release :)
